apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    tier: backend
  name: api
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: backend
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      serviceAccount: todo
      containers:
      - name: api
        image: beer1/todo-server-kotlin:0.1.0
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
        resources:
          requests: 
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
          - name: http
            protocol: TCP
            containerPort: 9000
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10

