apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    tier: backend
  name: api
  namespace: todo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: api
    tier: backend
