apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    tier: backend
  name: api
  namespace: todolist
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
    nodePort: 31000
  type: NodePort
  selector:
    app: api
    tier: backend
