apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      path: istio/example
  destination:
    name: ''
    namespace: bookinfo
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true