apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: middleware
spec:
  selector:
    matchLabels:
      app: mysql
      tier: middleware
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: middleware
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.30
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql
        volumeMounts:
          - name: config
            mountPath: /etc/mysql/conf.d
      volumes:
        - name: config
          configMap:
            name: mysql-conf
        